services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static-files:/app/out
    networks:
      - sist_net
  nginx:
    image: nginx:alpine
    networks:
      - sist_net
    restart: always
    volumes:
      - static-files:/usr/share/nginx/html:ro # ro: 읽기 전용
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    depends_on:
      - frontend

volumes:
  static-files:

networks:
  sist_net:
    driver: bridge
