name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Check if test script exists and run
      run: |
        if npm run | grep -q "^  test$"; then
          npm test
        else
          echo "No test script found, skipping tests"
        fi
  
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}
    
    # 디버깅을 위한 단계 추가
    - name: Debug SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
          whoami
          pwd
          ls -la /home/ubuntu
          if [ -d "/home/ubuntu/SIST-Docker" ]; then
            echo "Directory exists"
            ls -la /home/ubuntu/SIST-Docker
          else
            echo "Directory does not exist, creating..."
            mkdir -p /home/ubuntu/SIST-Docker
          fi
          echo "Setting permissions..."
          sudo chown -R ubuntu:ubuntu /home/ubuntu/SIST-Docker
          sudo chmod -R 777 /home/ubuntu/SIST-Docker
          ls -la /home/ubuntu/SIST-Docker
        EOF
    
    # 테스트 디렉토리에 먼저 복사 시도
    - name: Create test directory and try copying a single file
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
          mkdir -p /home/ubuntu/test-dir
          sudo chown -R ubuntu:ubuntu /home/ubuntu/test-dir
          sudo chmod -R 777 /home/ubuntu/test-dir
        EOF
        echo "Test content" > test.txt
        scp -v -o StrictHostKeyChecking=no test.txt ubuntu@${{ secrets.HOST }}:/home/ubuntu/test-dir/
    
    - name: Copy files to EC2 with verbose output
      run: |
        scp -v -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.HOST }}:/home/ubuntu/SIST-Docker
    
    - name: Deploy to EC2 and run Docker Compose
      if: ${{ success() }} # 이전 단계가 성공한 경우에만 실행
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
          cd /home/ubuntu/SIST-Docker
          docker-compose down
          docker-compose up -d --build
        EOF
