name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build --if-present
    
    - name: Check if test script exists and run
      run: |
        if npm run | grep -q "^  test$"; then
          npm test
        else
          echo "No test script found, skipping tests"
        fi
    
    # SCP 액션을 사용하여 파일 전송
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        source: ".,!node_modules"
        target: "/home/ubuntu/SIST-Docker"
        rm: true
    
    # SSH로 Docker Compose 실행
    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/SIST-Docker
          docker --version
          docker compose down || echo "docker compose down failed"
          docker compose up -d --build
